name: black check on push and PR
#
# Run the python formatting in check mode
#
on: [push, pull_request]

jobs:
  black-check:
     runs-on: ubuntu-latest
     steps:
        # Checkout the code
        - uses: actions/checkout@v2
        # Use the latest stable version of the github action
        - uses: psf/black@stable
          with:
             # Use options and version identical to the conda environment
             # Using pyproject.toml makes sure this testing is consistent with our python directory testing
             options: "--check --config python/pyproject.toml"
             src: "./python"
             # Version should be coordinated with the ctsm_pylib conda environment under the python directory
             version: "22.3.0"
          # Actions identical to above for each directory and source file we need to check (arrays aren't allowed for src: field)
        - uses: psf/black@stable
          with:
             options: "--check --config python/pyproject.toml"
             src: "./cime_config/SystemTests"
             version: "22.3.0"
        - uses: psf/black@stable
          with:
             options: "--check --config python/pyproject.toml"
             src: "./cime_config/buildlib"
             version: "22.3.0"
        - uses: psf/black@stable
          with:
             options: "--check --config python/pyproject.toml"
             src: "./cime_config/buildnml"
             version: "22.3.0"
